version: '3'

services:
  rabbit:
    image: rabbitmq:3.7.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    build: backend/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      - rabbit
  worker:
      build: worker/.
      environment:
        - SPRING_RABBITMQ_HOST=rabbit
      depends_on:
        - rabbit
